### ISSUE TITLE
Problem on merge when there is a conflict on comments

### ISSUE THREAD

**Issue by dlul** [DGA-MI-SSI/YaCo#10]
YaCo correctly detects a conflict when 2 users modify a comment on the same line without saving the IDB,
 but the saved data when resolving the conflict is random.

Example : user1 sets comment "toto" at line 1 and user2 sets "titi" at the same line.
user1 saves the IDB first. All is OK. user2 saves the IDB and gets a popup telling him there is a conflict, with "toto" and "titi" at line 1. He gets a text input area to enter the comment to be saved. User 2 sets "toto".

Expected : comment at line 1 is "toto".

Result : comment at line 1 is "random" (mix of "?" and alphanum characters).

The result is the same if user2 sets "titi" or "tutu" or whatever input he sets to resolve the conflict.
The same bug exists with repeatable comments.

Tested with IDA Linux 6.95.

**Comment by goulou** [comment]
_Split the bug with 2 distinct reports (see #11 )_
