### ISSUE TITLE
Document SSH authentication

### ISSUE THREAD

**Issue by trou** [DGA-MI-SSI/YaCo#18]
Hello,
I've just tried using YaCo using a remote repo which uses ssh keys with a passphrase.
It seems the current binary release can only use keys without passphrase.

I've just managed to use current git HEAD with an ssh-agent on Linux.

Is the ssh-agent auth going to work on Windows too ?

Either way it would be nice to have a small entry in the README to explain that :)

**Comment by bamiaux** [comment]
git HEAD support pageant on windows, that's what I'm using

**Comment by trou** [comment]
Maybe you could release a new binary for windows ?

**Comment by bamiaux** [comment]
https://github.com/DGA-MI-SSI/YaCo/releases/tag/v1.6
