### ISSUE TITLE
msbuild not able to configure libxml2

### ISSUE THREAD

**Issue by SBird1337** [DGA-MI-SSI/YaCo#19]
When using the configure scripts on msbuild (2015 or 2017) libxml2 will not be configured by cmake, and therefore the build fails.

CMake Error: CMake can not determine linker language for target: libxml2

**Comment by bamiaux** [comment]
Please add cmake configure line & CmakeError.log

**Comment by SBird1337** [comment]
here is the cmakeerror.log: https://pastebin.com/61sbftdJ
and the stdout: https://pastebin.com/RmyG6qdw

some of the msbuild output is in german i fear, thats just what msbuild does...

**Comment by bamiaux** [comment]
I don't see much, and my german is rusty
It looks like cmake is unable to see source files for libxml2, are they here ?
try this code in yadeps.cmake
```
get_files(files ${xml_dir})
get_files(includes ${xml_dir}/include OPTIONS recurse)
message("libxml files ${files} includes ${includes}")
```
