### ISSUE TITLE
IDA 7.0

### ISSUE THREAD

**Issue by Michael-Kelley** [DGA-MI-SSI/YaCo#20]
Are there any plans to update this to work with IDA 7.0?

**Comment by goulou** [comment]
Yeah it's coming : bamiaux already did the work, we're testing it before releasing...

**Comment by Michael-Kelley** [comment]
That's brilliant. Is there an estimated commit date?

**Comment by bamiaux** [comment]
Commits are pushed, no ETA on precompiled binaries though
