### ISSUE TITLE
x86 Arch

### ISSUE THREAD

**Issue by Michael-Kelley** [DGA-MI-SSI/YaCo#21]
Please re-implement the 32-bit build target. I regularly use IDA to analyse 32-bit code and make extensive use of the Hex-Rays decompiler plugin. As you may know, the 64-bit version of the decompiler plugin cannot be used on 32-bit code. I would like to be able to use YaCo to collaborate with other people, but I don't want to have to give up on the decompiler.

**Comment by bamiaux** [comment]
Correct me if I'm wrong but in IDA 6.95 we had
* idaq.exe 32-bit IDA for 32-bit targets
* idaq64.exe 32-bit IDA for 64-bit targets
Now with IDA 7, we have
* ida.exe 64-bit IDA for 32-bit targets
* ida64.exe 64-bit IDA for 64-bit targets
So you are still able to analyze & decompile 32-bit code/targets. It's just that the binary itself is 64-bit
I need to check, but I remember the 32-bit IDA version is not even in the default installer

**Comment by Michael-Kelley** [comment]
Yes, my apologies... I assumed without verifying that ida was a 32-bit process, and ida64 a 64-bit.  Both are indeed 64-bit on IDA 7.0.
