### ISSUE TITLE
Build on Windows fails when there is a space in the path to YaCo

### ISSUE THREAD

**Issue by fridtjof** [DGA-MI-SSI/YaCo#23]
Unfortunately I don't know cmake well enough to fix this in general because this occurs in a cmake file that is generated by configure_2017.cmd

Basically this is what goes wrong:
> CustomBuild:
  Building Custom Rule C:/Users/Fridtjof Mund/Desktop/YaCo/build/CMakeLists.txt
  CMake does not need to re-run because C:/Users/Fridtjof Mund/Desktop/YaCo/out/x64/CMakeFiles/generate.stamp is up-to-date.
  yadb.fbs
  Generating yatools_/git_version.dependency
  CMake Error at yatools_/git_version.cmake:2 (execute_process):
    execute_process given unknown argument "Mund/Desktop/YaCo".

This happens for me because my user directory has a space in it, which is how Windows 10 decided to create it.

**Comment by bamiaux** [comment]
Reproduced & fixed in https://github.com/DGA-MI-SSI/YaCo/tree/fix_path_quotes
Can you try it ?

**Comment by fridtjof** [comment]
Works! (after realizing a thing or two about quotes in env vars)
