### ISSUE TITLE
Non-repeatable comment creates both repeatable and non-repeatable comments

### ISSUE THREAD

**Issue by SpenserStyles** [DGA-MI-SSI/YaCo#29]
Using yatools-nt_x64-v1.6-0, saving an IDB with a non-repeatable comment creates both non-repeatable and repeatable comments.

**Comment by bamiaux** [comment]
Yes, v1.6 is broken sorry, a fix is incoming soon

**Comment by bamiaux** [comment]
Fixed in https://github.com/DGA-MI-SSI/YaCo/commit/e043c07d94d83c7f21bae34bdc575df173524851

**Comment by bamiaux** [comment]
Please try https://github.com/DGA-MI-SSI/YaCo/releases/tag/v1.7

**Comment by SpenserStyles** [comment]
I'll give it a try.  Thanks!
