### ISSUE TITLE
Failed to fetch origin, error: malformed URL

### ISSUE THREAD

**Issue by 7Hazard** [DGA-MI-SSI/YaCo#31]
``yaco: WARNING: Failed to fetch origin, error: malformed URL 'ssh://git@gitlab.com:HIDDEN/HIDDEN/HIDDEN.git'``
Sensetive or unimportant stuff has been replaced with HIDDEN
Using the latest build from releases

**Comment by bamiaux** [comment]
try to log with ssh & check whether ssh-agent or pageant is running
once it works, try with yaco

**Comment by SilverBut** [comment]
On Linux version:

```
$ cat vision_local.log                                                  
2018-04-25 16:50:56 yaco: YaCo version v1.8.3-0-ga6315501
2018-04-25 16:50:56 repo: warning Failed to get commit from master, error: no reference found for shorthand 'origin/master'
2018-04-25 16:50:56 repo: warning Master and origin/master does not point to same commit, please update your master
2018-04-25 16:52:04 events: cache: exported in 2 seconds
2018-04-25 16:52:04 repo: warning Failed to fetch origin, error: malformed URL 'ssh://DOMAIN/USER/FILE_2018.6.1_yaco.git'
2018-04-25 16:52:04 repo: warning Failed to rebase master from origin/master, error: no reference found for shorthand 'origin/master'
2018-04-25 16:52:04 repo: Unable to update cache
```

However:
```
$ ssh DOMAIN
PTY allocation request failed on channel 0
Welcome to GitLab, USER!
Connection to some.domain.example.com closed.
```

My `.ssh/config`:

```
Host DOMAIN
 IdentityFile ~/.ssh/USER@DOMAIN.key
 Port 13822
 User git
```

**Comment by SilverBut** [comment]
Seems YaCo is not reading this file?

**Comment by bamiaux** [comment]
YaCo is not using ssh directly, you need to use an SSH agent.
You can check instructions here https://www.ssh.com/ssh/agent
You probably need to do this
`
ssh-add ~/.ssh/USER@DOMAIN.key
`
It is probably possible to configure ssh-agent further to restrict this key to your domain only

**Comment by bamiaux** [comment]
ssh-add is the way to go on linux
I use pageant on windows, which is equivalent.
Can you try to connect to your github server using plink.exe instead of ssh and report the output ?

**Comment by paulsapps** [comment]
I managed to get it working with pageant. It was a little tricky because I had to use puttygen to generate a ppk for pageant but I couldn't get GitHub to accept that format. So I had to use puttygen again to get the public key in a format that GH was happy with.

**Comment by paulsapps** [comment]
Some extra hints for anyone who has this issue (specific to my repo sorry): https://gist.github.com/paulsapps/fdbcda15d6b268ab8b7d6683dc6c7dd7

**Comment by bamiaux** [comment]
Closing it as it should work with an ssh agent.
YaCo does not support .ssh/config files
