### ISSUE TITLE
Constant set as size of struct aren't kept in YaCo

### ISSUE THREAD

**Issue by cbayet** [DGA-MI-SSI/YaCo#34]
Hello,

It appears that when a constant is set in IDA as being the size of the struct
it is not save in YaCo and when closing and re-opening the database it is
lost.

An example will be: 
``add  eax, 20h`` becoming ``add eax, size MyStruct`` .
But when closing the IDA database and reopening it, it came back to being
``add eax, 20h`` .

We did not investigate where the problem came from.

**Comment by bamiaux** [comment]
I cannot reproduce it with 1.8.2 and IDA 7.1. Pressing "t", selecting a size, saving, re-opening keep the size applied

**Comment by cbayet** [comment]
Hi,

We didn't managed to reproduce it in a controlled environment either, so I close it for now and maybe we will retrieve the error case later.

Sorry for the fail
