### ISSUE TITLE
Changing the size of a structure embedded in an other structure is not supported

### ISSUE THREAD

**Issue by cbayet** [DGA-MI-SSI/YaCo#35]
Hi,

When a structure ``StructB`` is included in a ``StructA`` such as:

```

struct StructA {
	uint64_t	field_0;
	StructB		strb;
	uint64_t	field_x;
	uint64_t	field_y;
};
```

If the size of the ``StructB`` is increased by ``8`` bytes, the default behavior of IDA is to override the next field in the including structure:  ``field_x`` in ``StructA`` in our example. However when doing this in YaCo it appears to undefine the ``strb`` field in the ``StructA`` breaking a lot of references.

We did not investigate where this problem come from.

**Comment by bamiaux** [comment]
I cannot reproduce it, changing StructB size delete the association in StructA with IDA 7.1 with & without YaCo installed ?

**Comment by cbayet** [comment]
Hi,

It's an error from our tests, the result in IDA is effectively undefined and we didn't test properly our case (IDA doesn't behave the same way if the next field in defined or not).

Sorry for the fail !
