### ISSUE TITLE
Compilation failure on Windows

### ISSUE THREAD

**Issue by silverf0x** [DGA-MI-SSI/YaCo#4]
yaida32 project failed to compile with the following message:
fatal error C1083: Cannot open include file: 'bytes.hpp': No such file or directory

**Comment by goulou** [comment]
What is the line related to the error?
Which version of the IDA SDK are you building against?

**Comment by bamiaux** [comment]
bytes.hpp is part of IDA sdk
Make sure IDASDK_DIR is set properly, is different from IDA_DIR and that it contains an include directory
README.md will be amended to mention this

**Comment by proind** [comment]
I'm having the same problem , and I double checked my IDA_DIR  and IDASDK_DIR .
to be more specific :
set IDASDK_DIR="E:\idasdk695"
set IDA_DIR="C:\Program Files (x86)\IDA 6.95"

**Comment by bamiaux** [comment]
I'm not able to reproduce it.
However, cmake can store invalid values into cache which cannot overwritten with new values during configure.
Can you try to erase the output directory and try the cmake configure step from scratch ?
If you use configure_2015.cmd, you need to erase the "out" directory and try again
bytes.hpp should be in $IDASDK_DIR/include

**Comment by silverf0x** [comment]
ok, it works fine after erasing the out directory.

**Comment by bamiaux** [comment]
@proind does it work for you when configuring from scratch ?

**Comment by kitling** [comment]
There is another way for this to occur.

In my case, I set my environment variables like so:
```
set IDA_DIR="C:\Program Files (x86)\IDA Pro 6.8"
set IDASDK_DIR="C:\idasdk68"
```
and the resulting include path ended up as `C:\Users\Kitlith\src\YaCo\build\"C:\idasdk68"\include`

Fixing those paths in Visual Studio resulted in a clean build.

**Comment by bamiaux** [comment]
Remove the quotes and it should work without needing to fix paths in visual studio
```
set IDA_DIR=C:\Program Files (x86)\IDA Pro 6.8
set IDASDK_DIR=C:\idasdk68
```

**Comment by kitling** [comment]
... of course.

I'm too used to bash, so I habitually quote things like this, especially if there's spaces. >_>

So, anybody else that has this issue! Don't quote the values of the environment variables!
