### ISSUE TITLE
Freezes when asks for a remote origin

### ISSUE THREAD

**Issue by a1ext** [DGA-MI-SSI/YaCo#45]
Hi,

After the plugin had asked for a remote origin IDA showed `Running Python script` waitbox. So IDA just freezes and I neither enter it nor close any of dialogs/IDA windows.

![image](https://user-images.githubusercontent.com/14978853/42288612-203c2668-7fc4-11e8-8e5f-d6f64d45c76c.png)

This usually happens when a python script asks for some input and the ask box is not closed for some time. This could be solved using `execute_ui_requests`...

**Comment by bamiaux** [comment]
Sorry, I don't know how to reproduce it. Can you describe the steps involved ?
We're using ask_str to get the remote address, I've let it run for at least 5 minutes and I don't see any "Running python script".

**Comment by a1ext** [comment]
@bamiaux ok, I got it, it seems this was because of other plugin written in python, need to dig that.
Thanks
