### ISSUE TITLE
Are local types supported?

### ISSUE THREAD

**Issue by kalaider** [DGA-MI-SSI/YaCo#49]
It seems YaCo does not preserve any changes made in the Local Types view.

**Steps to reproduce.**

1. Create new local type (e.g. `struct my_struct { int a; };`) **and** sync it with the Structures view.
2. Use the new type somewhere (e.g. make some `dword_abcdef` of type `my_struct*`).
3. Save.
4. Force discard IDB and pull.
5. Type information is lost (and we have `import: error set_type: 0x89abcdef unknown type my_struct *` in the output window).

Local Types are very useful and it would be nice to fix (if a bug) or implement this (if a missing feature).

IDA 7.0 Windows version
YaCo 2.2

**Comment by bamiaux** [comment]
> On 22 Aug 2018, at 19:50, Vasilevsky Alexander <notifications@github.com> wrote:
> 
> It seems YaCo does not preserve any changes made in the Local Types view.
> 
> Steps to reproduce.
> 
> Create new local type (e.g. struct my_struct { int a; };) and sync it with the Structures view.
> Use the new type somewhere (e.g. make some dword_abcdef of type my_struct*).
> Save.
> Force discard IDB and pull.
> Type information is lost (and we have import: error set_type: 0x89abcdef unknown type my_struct * in the output window).
> Local Types are very useful and it would be nice to fix (if a bug) or implement this (if a missing feature).
> 

Thanks for creating an issue, it’s a missing feature.
It’s on my radar and I’ll get to it eventually.
It’s not easy though because of potential conflicts when two users add local types and use the same ordinals

**Comment by bamiaux** [comment]
@kalaider Fixed in https://github.com/DGA-MI-SSI/YaCo/commit/ef67a74c9fa9666da32ac6ed630fb824a9a8d370
Local types are now synchronized, it'll be in the next release if you cannot compile yaco

**Comment by bamiaux** [comment]
Should be fixed in https://github.com/DGA-MI-SSI/YaCo/releases/tag/v2.4
