### ISSUE TITLE
Provide binaries ?

### ISSUE THREAD

**Issue by trou** [DGA-MI-SSI/YaCo#5]
Compiling (at least on Linux) is a bit complex on 64-bits systems:
```
 python2.7-dev:i386 : Depends: python2.7:i386 (= 2.7.13-2) but it is not going to be installed
```
And the ABI of IDA is stable. So it would be nice if you could provide precompiled binaries (using Github releases ?).

**Comment by goulou** [comment]
Unfortunately, compiling binaries involves building against the IDA SDK, which we cannot easily provide for licensing reasons.
We are aware that this might be a blocker, a solution would be to provide a Docker instance "ready to build".

About your specific problem : are you sure your system (both 32 bits and 64 bits) is up to date? 
Apt refuses to install 32b libs if the version is not the same as the 64b currently installed, but the repository is coherent and both builds are the same version.

**Comment by goulou** [comment]
Unfortunately, compiling binaries involves building against the IDA SDK, which we cannot easily provide for licensing reasons.
We are aware that this might be a blocker, a solution would be to provide a Docker instance "ready to build".

About your specific problem : are you sure your system (both 32 bits and 64 bits) is up to date? 
Apt refuses to install 32b libs if the version is not the same as the 64b currently installed, but the repository is coherent and both builds are the same version.

**Comment by trou** [comment]
You can build against the SDK and distribute the resulting binaries without problem.

The problem is that on an amd64 debian (at least on Sid), you cannot install `python2.7-dev:i386` without pulling in the whole i386 python distribution, which is incompatible with the amd64 one.

And yes, they are the same version.

**Comment by goulou** [comment]
We are investigating that right now. We might upload binaries soon. 

Clould you try to install libpython2.7-dev:i386 instead of python2.7-dev:i386 and see if it works? If so, we will update the Readme accordingly.

**Comment by trou** [comment]
It works. Thanks.

**Comment by trou** [comment]
But you still should provide binaries ;)

**Comment by bamiaux** [comment]
It's a matter of days now, but ok, let's keep it open until then

**Comment by devnoname120** [comment]
Any news about binaries?

**Comment by bamiaux** [comment]
A binary release can be found here:
https://github.com/DGA-MI-SSI/YaCo/releases/tag/v1.5-6
