### ISSUE TITLE
Function colors not saved to xml/synchronized

### ISSUE THREAD

**Issue by Gericom** [DGA-MI-SSI/YaCo#50]
I noticed that the function colors which we use for tracking decompilation progress (like orange = started, green = done) are not synchronized between different users. The colors seem not to be saved to the xml, so it would be nice if that could be added, as it's quite an important feature for us.

![image](https://user-images.githubusercontent.com/5251038/44915587-a6e89d80-ad33-11e8-991a-f0c5a925360d.png)

**Comment by bamiaux** [comment]
I will add it, but IDA hooks may not notify us when you only change the function color
I'll check later
