### ISSUE TITLE
Windows 10 build failed

### ISSUE THREAD

**Issue by AmitRein** [DGA-MI-SSI/YaCo#58]
Trying to install YaCo at my local PC, getting an error while running cmake:

> $yaco/out/x64> cmake --build . --config RelWithDebInfo

Getting this error log:

> InitializeBuildStatus:
  Touching "yatools.dir\RelWithDebInfo\yatools.tlog\unsuccessfulbuild".
CustomBuild:
  yadb.fbs
  Generating yatools_/git_version.dependency
  fatal: not a git repository (or any of the parent directories): .git
  CMake Error at yatools_/git_version.cmake:9 (message):
    C:/Program Files/Git/cmd/git.exe describe --dirty --tags --long: returned
    128

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\ami
> tr\Documents\IDA\YaCo-master\out\x64\yatools.vcxproj]
> Done Building Project "C:\Users\amitr\Documents\IDA\YaCo-master\out\x64\yatools.vcxproj" (default targets) -- FAILED.
> 
> Done Building Project "C:\Users\amitr\Documents\IDA\YaCo-master\out\x64\yadifflib.vcxproj" (default targets) -- FAILED.
> 
> Done Building Project "C:\Users\amitr\Documents\IDA\YaCo-master\out\x64\_yatools_py32.vcxproj" (default targets) -- FAILED.
> 
> Project "C:\Users\amitr\Documents\IDA\YaCo-master\out\x64\ALL_BUILD.vcxproj" (1) is building "C:\Users\amitr\Documents\IDA\YaCo-master\out\x64\gtest.vcxproj" (23) on node 1 (default
>  targets).`

Has anyone encountered this? Can't figure out which repository is not a git repo, and why it should be.
Thanks!

**Comment by bamiaux** [comment]
You need to build the project from a git directory, because the git version is embedded into the dlls during compilation as a version string

**Comment by AmitRein** [comment]
That worked, thanks for the help (probably a silly question, I'm new to this)
