### ISSUE TITLE
module 'idc' has no attribute 'GetIdbPath' while opening IDA

### ISSUE THREAD

**Issue by AmitRein** [DGA-MI-SSI/YaCo#59]
Copied the release package to the plugin directory and receiving this error:

Failed while executing plugin_t.init():
module 'idc' has no attribute 'GetIdbPath'
  File "C:/Program Files/IDA Pro 7.5 SP3/plugins/yaco_plugin.py", line 63, in init
    input_filename = idc.GetIdbPath()

**Comment by AmitRein** [comment]
To fix this edit line 63 in yaco_plugin.py:
'GetIdbPath' -> 'get_idb_path'

**Comment by monster-oneday** [comment]
thank you so much
